name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is important for deployment
    steps:
      - uses: actions/checkout@v4 # Updated to v4 for better performance and security

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Updated to v4
        with:
          node-version: '18'
          cache: 'npm' # Added caching for faster installations

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4 # Updated to v4
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.ACCESS_TOKEN }} # Added token for authentication
